<?php

namespace ScrumBundle\Repository;

/**
 * epicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class epicRepository extends \Doctrine\ORM\EntityRepository
{
}
