<?php

namespace ScrumBundle\Repository;

/**
 * project_userRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class project_userRepository extends \Doctrine\ORM\EntityRepository
{
}
