<?php

namespace ScrumBundle\Repository;

/**
 * user_storyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class user_storyRepository extends \Doctrine\ORM\EntityRepository
{
}
